catalog:
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
minimumReleaseAgeExclude:
  - "@vizejs/native-darwin-arm64@0.230.0"
  - "@vizejs/native-darwin-x64@0.230.0"
  - "@vizejs/native-linux-arm64-gnu@0.230.0"
  - "@vizejs/native-linux-arm64-musl@0.230.0"
  - "@vizejs/native-linux-x64-gnu@0.230.0"
  - "@vizejs/native-linux-x64-musl@0.230.0"
  - "@vizejs/native-win32-arm64-msvc@0.230.0"
  - "@vizejs/native-win32-x64-msvc@0.230.0"
  - "@vizejs/native@0.230.0"
  - "@vizejs/vite-plugin@0.230.0"
  - vize@0.230.0
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
